// Package workspace guards against sandboxing directories that cannot be
// safely bind-mounted (the home directory or filesystem root) by redirecting
// to a dated workspace under ~/asylum-workspace/.
package workspace

import (
	"bufio"
	"bytes"
	"math/rand"
	"os"
	"path/filepath"
	"regexp"
	"slices"
	"strings"
	"time"

	"github.com/inventage-ai/asylum/assets"
)

var words = parseWords(assets.WorkspaceWords)

// namePattern matches the names generated by name, so hand-made directories
// under ~/asylum-workspace/ are never picked for reuse.
var namePattern = regexp.MustCompile(`^\d{4}-\d{2}-\d{2}(-[a-z]+){3}$`)

// Outcome reports what Resolve did with the project directory.
type Outcome int

const (
	Unchanged Outcome = iota // safe directory, used as-is
	Fresh                    // new workspace created
	Continued                // existing workspace with an agent session
	Attached                 // existing workspace with a running container
)

func parseWords(data []byte) []string {
	var out []string
	sc := bufio.NewScanner(bytes.NewReader(data))
	for sc.Scan() {
		if w := strings.TrimSpace(sc.Text()); w != "" {
			out = append(out, w)
		}
	}
	return out
}

// unsafe reports whether dir cannot be safely sandboxed: the exact home
// directory or the filesystem root. Subdirectories of home are safe.
func unsafe(dir, home string) bool {
	dir = filepath.Clean(dir)
	return dir == filepath.Clean(home) || dir == string(filepath.Separator)
}

func name(date string, r *rand.Rand) string {
	w := func() string { return words[r.Intn(len(words))] }
	return date + "-" + w() + "-" + w() + "-" + w()
}

// Resolve returns projectDir unchanged when it is safe to sandbox. When it is
// the home directory or filesystem root, it redirects to a workspace under
// ~/asylum-workspace/: the most recently modified existing workspace that
// accept allows, reported as match, or else a fresh
// <YYYY-MM-DD>-<three-words>/ directory. A nil accept always creates a fresh one.
func Resolve(projectDir, home string, accept func(dir string) bool, match Outcome) (string, Outcome, error) {
	if !unsafe(projectDir, home) {
		return projectDir, Unchanged, nil
	}
	base := filepath.Join(home, "asylum-workspace")
	if accept != nil {
		dir, err := newest(base, accept)
		if err != nil {
			return "", Unchanged, err
		}
		if dir != "" {
			return dir, match, nil
		}
	}
	r := rand.New(rand.NewSource(time.Now().UnixNano()))
	dir, err := create(base, time.Now().Format("2006-01-02"), r)
	if err != nil {
		return "", Unchanged, err
	}
	return dir, Fresh, nil
}

// newest returns the most recently modified generated workspace under base
// that accept allows, or "" when there is none.
func newest(base string, accept func(string) bool) (string, error) {
	entries, err := os.ReadDir(base)
	if os.IsNotExist(err) {
		return "", nil
	}
	if err != nil {
		return "", err
	}
	type candidate struct {
		dir   string
		mtime time.Time
	}
	var candidates []candidate
	for _, e := range entries {
		if !e.IsDir() || !namePattern.MatchString(e.Name()) {
			continue
		}
		info, err := e.Info()
		if err != nil {
			continue
		}
		candidates = append(candidates, candidate{filepath.Join(base, e.Name()), info.ModTime()})
	}
	slices.SortFunc(candidates, func(a, b candidate) int { return b.mtime.Compare(a.mtime) })
	for _, c := range candidates {
		if accept(c.dir) {
			return c.dir, nil
		}
	}
	return "", nil
}

func create(base, date string, r *rand.Rand) (string, error) {
	for {
		dir := filepath.Join(base, name(date, r))
		_, err := os.Stat(dir)
		if err == nil {
			continue // collision — re-roll the words
		}
		if !os.IsNotExist(err) {
			return "", err
		}
		if err := os.MkdirAll(dir, 0o755); err != nil {
			return "", err
		}
		return dir, nil
	}
}
